import type { Game, GameKind, Prompt } from '../types'

const exampleReels: Partial<Record<GameKind, string>> = {
  'find-number': 'https://www.instagram.com/reel/DcAko4WN2m0/?utm_source=ig_web_copy_link',
  sketch: 'https://www.instagram.com/reel/DdHvFejv65y/?utm_source=ig_web_copy_link',
  'race-3': 'https://www.instagram.com/reel/DcpFNjsvfuh/?utm_source=ig_web_copy_link',
  'forbidden-number': 'https://www.instagram.com/reel/Dbbb1owSJlG/?utm_source=ig_web_copy_link',
  uno: 'https://www.instagram.com/reel/DcaSdFHyL9E/?utm_source=ig_web_copy_link',
}

export const defaultGames: Game[] = [
  { id:'g01', slug:'uno', name:'UNO Game', shortDescription:'Play physical UNO. Let the room handle the scores.', description:'A scorekeeper for a real UNO table. Keep your physical deck; the app handles the running totals.', instructions:['Create a room and add everyone at the table.','Play UNO normally with the physical deck.','After each hand, enter the points for the winner or losing players.','Keep playing until the table reaches the agreed score.'], exampleUrl:exampleReels.uno, scoreMode:'uno', animationKey:'cards', tags:['card game','scoreboard','classic'] },
  { id:'g02', slug:'forbidden-number', name:'Don’t Say X', shortDescription:'Pick a number. Say it and you lose.', description:'A counting trap. Choose a forbidden number before the round and count around the group without saying it.', instructions:['Choose the forbidden number, such as 21.','Players count upward in order.','Agree how many numbers a player may say on a turn.','Whoever says the forbidden number loses the round.'], exampleUrl:exampleReels['forbidden-number'], scoreMode:'points', animationKey:'counting', tags:['counting','elimination','reaction'], isSoloFriendly:true },
  { id:'g03', slug:'opposite-action', name:'Stay Different', shortDescription:'Do the opposite. Be the last player still wrong on purpose.', description:'The host sets an action such as sit/stand. Players try to stay opposite to the majority; the last player successfully avoiding the group wins.', instructions:['Choose two opposite actions: sit / stand is the easiest.','Host gives rapid commands or changes the majority action.','Your goal is to be the last person not matching the group.','Award the round point to the last player who stays different.'], scoreMode:'points', animationKey:'mirror', tags:['reaction','group','movement'] },
  { id:'g04', slug:'race-3', name:'Get to 3', shortDescription:'Win three rounds before everyone else.', description:'A clean first-to-three race. The app is the round counter and scoreboard.', instructions:['Create a room and get everyone ready.','Run the physical challenge for the round.','Host awards one point to the round winner.','First player to 3 points wins the game.'], exampleUrl:exampleReels['race-3'], scoreMode:'race', targetScore:3, animationKey:'race3', tags:['race','score','quick'] },
  { id:'g05', slug:'sketch', name:'Sketch Game', shortDescription:'Draw the prompt. Let everyone else guess.', description:'A drawing round with a built-in canvas and prompt deck. Keep the real-world guessing around the screen.', instructions:['Choose a drawer and give them a secret prompt.','The drawer sketches without writing words or letters.','Everyone else guesses aloud.','Give the point to the first correct guess and move to the next drawer.'], exampleUrl:exampleReels.sketch, scoreMode:'points', animationKey:'sketch', tags:['drawing','guessing','creative'], isSoloFriendly:true },
  { id:'g06', slug:'find-number', name:'Find the Number', shortDescription:'Race to spot the number first.', description:'A visual reaction game where the host reveals a target and the fastest correct player takes the point.', instructions:['Host chooses or reveals a number.','Everyone searches the visual challenge at the same time.','First player to call the correct number wins the round.','Record the winner and start again.'], exampleUrl:exampleReels['find-number'], scoreMode:'points', animationKey:'search', tags:['visual','numbers','reaction'] },
  { id:'g07', slug:'guess-leader', name:'Guess the Leader', shortDescription:'Figure out who is secretly leading the group.', description:'One player is the leader and the rest follow. A guesser watches closely and tries to identify the leader.', instructions:['Send one guesser away or have them close their eyes.','Pick a secret leader.','The leader changes actions while everyone mirrors them.','Bring the guesser back; they get a limited number of guesses.'], scoreMode:'points', animationKey:'leader', tags:['social','bluff','guessing'] },
  { id:'g08', slug:'guess-number', name:'Guess the Number', shortDescription:'Closest guess wins the round.', description:'Choose a hidden number inside an agreed range. Players make guesses until somebody gets it or the host reveals it.', instructions:['Choose a range, such as 1–100.','Host secretly picks a target number.','Players take turns guessing.','Award the point to the closest or first exact guess, depending on your house rules.'], scoreMode:'points', animationKey:'target', tags:['numbers','guessing','party'], isSoloFriendly:true },
  { id:'g09', slug:'ten-seconds', name:'10 Seconds', shortDescription:'Trust your internal clock.', description:'Try to hit exactly ten seconds without a visible timer.', instructions:['Start the round and have players close their eyes or turn away.','Each player says stop when they think 10 seconds have passed.','Host checks the real elapsed time.','Closest to 10.00 seconds wins the round.'], scoreMode:'points', animationKey:'timer', tags:['timing','reaction','challenge'], isSoloFriendly:true },
  { id:'g10', slug:'memory-drawing', name:'Memory Drawing', shortDescription:'Look. Hide. Draw from memory.', description:'Study a simple object or scene for a few seconds, hide it, then recreate it from memory.', instructions:['Choose a prompt and show the reference briefly.','Hide the reference.','Players draw what they remember.','Host judges the closest drawing or lets the group vote.'], scoreMode:'points', animationKey:'memory', tags:['drawing','memory','creative'], isSoloFriendly:true },
  { id:'g11', slug:'race-5', name:'First to 5', shortDescription:'Win five rounds before anyone else.', description:'A fast score race for games where each completed challenge is worth one point.', instructions:['Start a room with all players.','Play one physical round.','Host awards one point to the winner.','First player to 5 points wins.'], scoreMode:'race', targetScore:5, animationKey:'race5', tags:['race','score','classic'] },
  { id:'g12', slug:'wrong-answers', name:'Wrong Answers Only', shortDescription:'Answer incorrectly — but answer fast.', description:'Questions are easy; the trick is never giving the correct answer. Award points for the funniest or quickest valid wrong answer.', instructions:['Host reads a simple question.','Every response must be deliberately wrong.','No repeating an earlier answer.','Award the point to the best response of the round.'], scoreMode:'points', animationKey:'wrong', tags:['questions','funny','speed'], isSoloFriendly:true },
  { id:'g13', slug:'contact', name:'Contact', shortDescription:'Use the word deck and make a connection.', description:'A word-based party game. The app provides a rotating prompt deck; the host controls who connects the clue to the target word.', instructions:['Pick a target word from the deck.','Host gives the agreed starting clue or letter.','Players offer clues without saying the target word.','When two players think they have the same answer, call “contact” and compare.'], scoreMode:'points', animationKey:'contact', tags:['words','communication','party'] },
  { id:'g14', slug:'hsk-cup', name:'Head, Shoulders, Knees & Cup', shortDescription:'Follow the body calls — grab the cup first.', description:'A reflex game with four positions and a cup. The caller tries to catch players reacting early.', instructions:['Put one cup between the players.','Call head, shoulders, knees in random order.','On “cup”, grab the cup immediately.','False starts lose the point; first clean grab wins.'], scoreMode:'points', animationKey:'cup', tags:['reaction','movement','duel'] },
  { id:'g15', slug:'garbage', name:'Garbage', shortDescription:'Physical card game + digital score tracker.', description:'Use the app for rounds, winners and house scoring while the real deck stays on the table.', instructions:['Set up the Garbage card game with the physical deck.','Create a room and add players.','After a round, record the result in the scoreboard.','Repeat until your table decides the winner.'], scoreMode:'manual', animationKey:'garbage', tags:['card game','scorekeeper','strategy'] },
  { id:'g16', slug:'pressure', name:'Pressure', shortDescription:'Physical card game with a shared score table.', description:'Run the card game in real life and use the app to track rounds, pressure points and the final winner.', instructions:['Deal and set up the physical game according to your house rules.','Play the round completely offline from the app.','Host records who won the round and the points.','Use the running table to keep everyone honest.'], scoreMode:'manual', animationKey:'pressure', tags:['card game','scorekeeper','strategy'] },
]

export const defaultPrompts: Prompt[] = [
  ...['cat','guitar','pizza','airplane','toothbrush','elephant','football','umbrella','bicycle','rocket'].map((x, i) => ({id:`sketch-${i}`, gameId:'g05', prompt:x, difficulty:'easy' as const})),
  ...['lighthouse','photographer','washing machine','treasure chest','campfire','roller coaster','birthday surprise','traffic jam'].map((x, i) => ({id:`sketch-m-${i}`, gameId:'g05', prompt:x, difficulty:'medium' as const})),
  ...['time machine','underwater restaurant','alien trying to cook','dragon at the airport','robot getting a haircut','haunted supermarket'].map((x, i) => ({id:`sketch-h-${i}`, gameId:'g05', prompt:x, difficulty:'hard' as const})),
  ...['balloon','tree','chair','fish','sun','house','coffee mug','shoe','key','book'].map((x, i) => ({id:`memory-e-${i}`, gameId:'g10', prompt:x, difficulty:'easy' as const})),
  ...['bicycle with basket','person at a bus stop','table with three objects','park bench','kitchen counter','bedroom desk','market stall','simple robot'].map((x, i) => ({id:`memory-m-${i}`, gameId:'g10', prompt:x, difficulty:'medium' as const})),
  ...['busy street scene','game-night table from above','space station control room','crowded restaurant','playground with five objects','imaginary machine with many parts'].map((x, i) => ({id:`memory-h-${i}`, gameId:'g10', prompt:x, difficulty:'hard' as const})),
  ...['What color is the sky?','How many days are in a week?','What do you drink when thirsty?','What animal says meow?','What do you use to cut paper?','What planet do we live on?','What is 2 + 2?','What do you wear on your feet?','What do you open a door with?','What do bees make?'].map((x, i) => ({id:`wrong-${i}`, gameId:'g12', prompt:x})),
  ...['apple','school','phone','river','window','doctor','train','banana','hospital','holiday','garden','music'].map((x, i) => ({id:`contact-${i}`, gameId:'g13', prompt:x})),
]

export function gameBySlug(slug: GameKind) { return defaultGames.find(g => g.slug === slug) }
