import type { Game, GameKind, Prompt } from '../types'

const exampleReels: Partial<Record<GameKind, string>> = {
  'find-number': 'https://www.instagram.com/reel/DcAko4WN2m0/?utm_source=ig_web_copy_link',
  sketch: 'https://www.instagram.com/reel/DdHvFejv65y/?utm_source=ig_web_copy_link',
  'race-3': 'https://www.instagram.com/reel/DcpFNjsvfuh/?utm_source=ig_web_copy_link',
  'forbidden-number': 'https://www.instagram.com/reel/Dbbb1owSJlG/?utm_source=ig_web_copy_link',
  uno: 'https://www.instagram.com/reel/DcaSdFHyL9E/?utm_source=ig_web_copy_link',
}

export const defaultGames: Game[] = [
  { id:'g01', slug:'uno', name:'UNO Game', shortDescription:'Play physical UNO. Let the room handle the scores.', description:'A scorekeeper for a real UNO table. Keep your physical deck; the app handles the running totals.', instructions:['Create a room and add everyone at the table.','Play UNO normally with the physical deck.','After each hand, enter the points for the winner or losing players.','Keep playing until the table reaches the agreed score.'], exampleUrl:exampleReels.uno, scoreMode:'uno', animationKey:'cards', tags:['card game','scoreboard','classic'] },
  { id:'g02', slug:'forbidden-number', name:'Don’t Say X', shortDescription:'Pick a number. Say it and you lose.', description:'A counting trap. Choose a forbidden number before the round and count around the group without saying it.', instructions:['Choose the forbidden number, such as 21.','Players count upward in order.','Agree how many numbers a player may say on a turn.','Whoever says the forbidden number loses the round.'], exampleUrl:exampleReels['forbidden-number'], scoreMode:'points', animationKey:'counting', tags:['counting','elimination','reaction'] },
  { id:'g03', slug:'opposite-action', name:'Stay Different', shortDescription:'Do the opposite. Be the last player still wrong on purpose.', description:'The host sets an action such as sit/stand. Players try to stay opposite to the majority; the last player successfully avoiding the group wins.', instructions:['Choose two opposite actions: sit / stand is the easiest.','Host gives rapid commands or changes the majority action.','Your goal is to be the last person not matching the group.','Award the round point to the last player who stays different.'], scoreMode:'points', animationKey:'mirror', tags:['reaction','group','movement'] },
  { id:'g04', slug:'race-3', name:'Get to 3', shortDescription:'Win three rounds before everyone else.', description:'A clean first-to-three race. The app is the round counter and scoreboard.', instructions:['Create a room and get everyone ready.','Run the physical challenge for the round.','Host awards one point to the round winner.','First player to 3 points wins the game.'], exampleUrl:exampleReels['race-3'], scoreMode:'race', targetScore:3, animationKey:'race3', tags:['race','score','quick'] },
  { id:'g05', slug:'sketch', name:'Sketch Game', shortDescription:'Draw the prompt. Let everyone else guess.', description:'A drawing round with a built-in canvas and prompt deck. Keep the real-world guessing around the screen.', instructions:['Choose a drawer and give them a secret prompt.','The drawer sketches without writing words or letters.','Everyone else guesses aloud.','Give the point to the first correct guess and move to the next drawer.'], exampleUrl:exampleReels.sketch, scoreMode:'points', animationKey:'sketch', tags:['drawing','guessing','creative'] },
  { id:'g06', slug:'find-number', name:'Find the Number', shortDescription:'Race to spot the number first.', description:'A visual reaction game where the host reveals a target and the fastest correct player takes the point.', instructions:['Host chooses or reveals a number.','Everyone searches the visual challenge at the same time.','First player to call the correct number wins the round.','Record the winner and start again.'], exampleUrl:exampleReels['find-number'], scoreMode:'points', animationKey:'search', tags:['visual','numbers','reaction'] },
  { id:'g07', slug:'guess-leader', name:'Guess the Leader', shortDescription:'Figure out who is secretly leading the group.', description:'One player is the leader and the rest follow. A guesser watches closely and tries to identify the leader.', instructions:['Send one guesser away or have them close their eyes.','Pick a secret leader.','The leader changes actions while everyone mirrors them.','Bring the guesser back; they get a limited number of guesses.'], scoreMode:'points', animationKey:'leader', tags:['social','bluff','guessing'] },
  { id:'g08', slug:'guess-number', name:'Guess the Number', shortDescription:'Closest guess wins the round.', description:'Choose a hidden number inside an agreed range. Players make guesses until somebody gets it or the host reveals it.', instructions:['Choose a range, such as 1–100.','Host secretly picks a target number.','Players take turns guessing.','Award the point to the closest or first exact guess, depending on your house rules.'], scoreMode:'points', animationKey:'target', tags:['numbers','guessing','party'] },
  { id:'g09', slug:'ten-seconds', name:'10 Seconds', shortDescription:'Trust your internal clock.', description:'Try to hit exactly ten seconds without a visible timer.', instructions:['Start the round and have players close their eyes or turn away.','Each player says stop when they think 10 seconds have passed.','Host checks the real elapsed time.','Closest to 10.00 seconds wins the round.'], scoreMode:'points', animationKey:'timer', tags:['timing','reaction','challenge'], isSoloFriendly:true },
  { id:'g10', slug:'memory-drawing', name:'Memory Drawing', shortDescription:'Look. Hide. Draw from memory.', description:'Study a simple object or scene for a few seconds, hide it, then recreate it from memory.', instructions:['Choose a prompt and show the reference briefly.','Hide the reference.','Players draw what they remember.','Host judges the closest drawing or lets the group vote.'], scoreMode:'points', animationKey:'memory', tags:['drawing','memory','creative'] },
  { id:'g11', slug:'race-5', name:'First to 5', shortDescription:'Win five rounds before anyone else.', description:'A fast score race for games where each completed challenge is worth one point.', instructions:['Start a room with all players.','Play one physical round.','Host awards one point to the winner.','First player to 5 points wins.'], scoreMode:'race', targetScore:5, animationKey:'race5', tags:['race','score','classic'] },
  { id:'g12', slug:'wrong-answers', name:'Wrong Answers Only', shortDescription:'Answer incorrectly — but answer fast.', description:'Questions are easy; the trick is never giving the correct answer. Award points for the funniest or quickest valid wrong answer.', instructions:['Host reads a simple question.','Every response must be deliberately wrong.','No repeating an earlier answer.','Award the point to the best response of the round.'], scoreMode:'points', animationKey:'wrong', tags:['questions','funny','speed'] },
  { id:'g13', slug:'contact', name:'Contact', shortDescription:'Use the word deck and make a connection.', description:'A word-based party game. The app provides a rotating prompt deck; the host controls who connects the clue to the target word.', instructions:['Pick a target word from the deck.','Host gives the agreed starting clue or letter.','Players offer clues without saying the target word.','When two players think they have the same answer, call “contact” and compare.'], scoreMode:'points', animationKey:'contact', tags:['words','communication','party'] },
  { id:'g14', slug:'hsk-cup', name:'Head, Shoulders, Knees & Cup', shortDescription:'Follow the body calls — grab the cup first.', description:'A reflex game with four positions and a cup. The caller tries to catch players reacting early.', instructions:['Put one cup between the players.','Call head, shoulders, knees in random order.','On “cup”, grab the cup immediately.','False starts lose the point; first clean grab wins.'], scoreMode:'points', animationKey:'cup', tags:['reaction','movement','duel'] },
  { id:'g15', slug:'garbage', name:'Garbage', shortDescription:'Physical card game + digital score tracker.', description:'Use the app for rounds, winners and house scoring while the real deck stays on the table.', instructions:['Set up the Garbage card game with the physical deck.','Create a room and add players.','After a round, record the result in the scoreboard.','Repeat until your table decides the winner.'], scoreMode:'manual', animationKey:'garbage', tags:['card game','scorekeeper','strategy'] },
  { id:'g16', slug:'pressure', name:'Pressure', shortDescription:'Physical card game with a shared score table.', description:'Run the card game in real life and use the app to track rounds, pressure points and the final winner.', instructions:['Deal and set up the physical game according to your house rules.','Play the round completely offline from the app.','Host records who won the round and the points.','Use the running table to keep everyone honest.'], scoreMode:'manual', animationKey:'pressure', tags:['card game','scorekeeper','strategy'] },
  { id:'online-skribbl', slug:'skribbl', behavior:'online', name:'Skribbl.io', shortDescription:'Draw, guess and laugh together online.', description:'Open a live Skribbl.io room from Game Night and bring everyone into the same drawing-and-guessing match.', instructions:['Create a Game Night room.','Open Skribbl.io and choose Create Private Room.','Copy the generated invite link into the Game Night room so everyone can launch the same match.','Use the Game Night chat while you wait and play.'], scoreMode:'manual', minPlayers:2, animationKey:'sketch', tags:['online','drawing','multiplayer','pictionary'], playMode:'online', externalProvider:'Skribbl.io', externalLaunchUrl:'https://skribbl.io/', isSoloFriendly:false },
  { id:'online-gartic-phone', slug:'gartic-phone', behavior:'online', name:'Gartic Phone', shortDescription:'Write, draw and reveal the funniest chain online.', description:'Use Gartic Phone for a telephone-style drawing game where each player writes and draws, then watches the chain unfold.', instructions:['Create a Game Night room.','Open Gartic Phone and create or join a lobby.','Copy the room URL into Game Night so the whole group can launch it.','Keep Game Night chat open for coordination.'], scoreMode:'manual', minPlayers:2, animationKey:'sketch', tags:['online','drawing','telephone','multiplayer'], playMode:'online', externalProvider:'Gartic Phone', externalLaunchUrl:'https://garticphone.com/en/lobby', isSoloFriendly:false },
  { id:'online-codenames', slug:'codenames-online', behavior:'online', name:'Codenames Online', shortDescription:'Play the classic clue-and-guess word game online.', description:'Codenames Online lets the group create a room and share a room URL for a live browser match.', instructions:['Create a Game Night room.','Open Codenames Online and create a room.','Copy the room URL into Game Night.','Share the Game Night room with your players and launch the same Codenames room.'], scoreMode:'manual', minPlayers:4, supportsTeams:true, animationKey:'contact', tags:['online','words','teams','multiplayer'], playMode:'online', externalProvider:'Codenames Online', externalLaunchUrl:'https://codenames.game/', isSoloFriendly:false },
  { id:'online-jigsaw', slug:'jigsaw-explorer', behavior:'online', name:'Jigsaw Explorer', shortDescription:'Solve one jigsaw together in real time.', description:'Jigsaw Explorer supports multiplayer puzzles through a shareable game link.', instructions:['Create a Game Night room.','Choose a puzzle on Jigsaw Explorer and switch it to multiplayer mode.','Copy the generated multiplayer link into Game Night.','Everyone opens the same link and works on the puzzle together.'], scoreMode:'manual', minPlayers:2, animationKey:'memory', tags:['online','puzzle','jigsaw','co-op'], playMode:'online', externalProvider:'Jigsaw Explorer', externalLaunchUrl:'https://www.jigsawexplorer.com/', isSoloFriendly:false },
  { id:'online-playingcards', slug:'playingcards-io', behavior:'online', name:'PlayingCards.io', shortDescription:'Free synchronized virtual tables for cards and board games.', description:'PlayingCards.io offers free multiplayer rooms for many classic card and tabletop games with synchronized moves.', instructions:['Create a Game Night room.','Open PlayingCards.io and select a game.','Create a room and copy its room code or link into Game Night.','Players launch the same table and play together.'], scoreMode:'manual', minPlayers:2, animationKey:'cards', tags:['online','cards','board game','multiplayer'], playMode:'online', externalProvider:'PlayingCards.io', externalLaunchUrl:'https://playingcards.io/games/', isSoloFriendly:false },
  { id:'online-bga', slug:'board-game-arena', behavior:'online', name:'Board Game Arena', shortDescription:'Play hundreds of browser board games with friends.', description:'Board Game Arena offers free browser play across a large collection of board games. Some games or features may have availability restrictions.', instructions:['Create a Game Night room.','Open Board Game Arena and choose a game available to your group.','Create a private table or invite your friends there.','Paste the table invite link into Game Night so everyone can launch it.'], scoreMode:'manual', minPlayers:2, animationKey:'race5', tags:['online','board game','strategy','multiplayer'], playMode:'online', externalProvider:'Board Game Arena', externalLaunchUrl:'https://en.boardgamearena.com/', isSoloFriendly:false },

  { id:'online-sketchful', slug:'sketchful', behavior:'online', name:'Sketchful.io', shortDescription:'Free online Pictionary with private rooms.', description:'Sketchful.io is a browser drawing-and-guessing game with private lobby links and configurable rounds.', instructions:['Create a Game Night room.','Open Sketchful.io and create a lobby.','Copy the room link into Game Night.','Everyone opens the same Sketchful lobby to play together.'], scoreMode:'manual', minPlayers:2, animationKey:'sketch', tags:['online','drawing','pictionary','multiplayer'], playMode:'online', externalProvider:'Sketchful.io', externalLaunchUrl:'https://sketchful.io/' },
  { id:'online-gartic', slug:'gartic-io', behavior:'online', name:'Gartic.io', shortDescription:'Draw and guess in a shared online room.', description:'Gartic.io provides live drawing-and-guessing rooms that friends can join from a shared room link.', instructions:['Create a Game Night room.','Open Gartic.io and create or choose a room.','Share the Gartic room link with your Game Night players.','Keep Game Night chat available for coordination.'], scoreMode:'manual', minPlayers:2, animationKey:'sketch', tags:['online','drawing','guessing','multiplayer'], playMode:'online', externalProvider:'Gartic.io', externalLaunchUrl:'https://gartic.io/' },
  { id:'online-bombparty', slug:'bombparty', behavior:'online', name:'BombParty', shortDescription:'Fast word battles with a room code.', description:'BombParty on JKLM.FUN is a fast-paced word game with private rooms and a shared code.', instructions:['Create a Game Night room.','Open JKLM.FUN and start a private room.','Give the private room code to your Game Night group.','Everyone joins the same BombParty room and plays.'], scoreMode:'manual', minPlayers:2, animationKey:'wrong', tags:['online','words','party','multiplayer'], playMode:'online', externalProvider:'JKLM.FUN', externalLaunchUrl:'https://jklm.fun/' },
  { id:'online-bonk', slug:'bonk-io', behavior:'online', name:'Bonk.io', shortDescription:'Physics battles with custom rooms.', description:'Bonk.io is a browser physics multiplayer game supporting custom games and private play with friends.', instructions:['Create a Game Night room.','Open Bonk.io and create a custom game.','Share the room/game invite with your Game Night players.','Join the same Bonk.io match and battle.'], scoreMode:'manual', minPlayers:2, animationKey:'race5', tags:['online','action','physics','multiplayer'], playMode:'online', externalProvider:'Bonk.io', externalLaunchUrl:'https://bonk.io/' },
  { id:'online-haxball', slug:'haxball', behavior:'online', name:'HaxBall', shortDescription:'Fast browser football in private rooms.', description:'HaxBall is a real-time physics football game with room hosting and built-in chat.', instructions:['Create a Game Night room.','Open HaxBall and create or join a room.','Share the HaxBall room link/code with your group.','Play together while using Game Night chat for coordination.'], scoreMode:'manual', minPlayers:2, animationKey:'race3', tags:['online','sports','football','multiplayer'], playMode:'online', externalProvider:'HaxBall', externalLaunchUrl:'https://www.haxball.com/' },
  { id:'online-tetrio', slug:'tetrio', behavior:'online', name:'TETR.IO', shortDescription:'Create private multiplayer rooms for modern Tetris.', description:'TETR.IO offers free multiplayer play and custom private rooms that can be joined by room ID or URL.', instructions:['Create a Game Night room.','Open TETR.IO and choose Custom Game.','Create a private room and copy the room ID or URL.','Share it in your Game Night room so everyone joins the same match.'], scoreMode:'manual', minPlayers:2, animationKey:'race3', tags:['online','puzzle','arcade','multiplayer'], playMode:'online', externalProvider:'TETR.IO', externalLaunchUrl:'https://tetr.io/' },
  { id:'online-lichess', slug:'lichess', behavior:'online', name:'Lichess', shortDescription:'Free online chess with direct friend challenges.', description:'Lichess is a free, open-source chess server with direct challenges and live games.', instructions:['Create a Game Night room.','Open Lichess and use Challenge a friend.','Copy or share the resulting game/invite with your opponent.','Keep the Game Night room open for coordination.'], scoreMode:'manual', minPlayers:2, animationKey:'contact', tags:['online','chess','strategy','multiplayer'], playMode:'online', externalProvider:'Lichess', externalLaunchUrl:'https://lichess.org/' },
  { id:'online-pokemon-showdown', slug:'pokemon-showdown', behavior:'online', name:'Pokémon Showdown', shortDescription:'Challenge a friend to a browser Pokémon battle.', description:'Pokémon Showdown supports direct challenges between named players in its browser client.', instructions:['Create a Game Night room.','Open Pokémon Showdown and set your username.','Use Challenge on your friend or create the agreed battle format.','Share your usernames with the Game Night group and battle together.'], scoreMode:'manual', minPlayers:2, animationKey:'race5', tags:['online','strategy','battle','multiplayer'], playMode:'online', externalProvider:'Pokémon Showdown', externalLaunchUrl:'https://pokemonshowdown.com/' },
  { id:'online-papergames-connect4', slug:'papergames-connect4', behavior:'online', name:'Connect 4 — papergames.io', shortDescription:'Free two-player Connect 4 with a shareable link.', description:'papergames.io offers free real-time paper-and-pencil classics including Connect 4, Gomoku and Tic-Tac-Toe.', instructions:['Create a Game Night room.','Open papergames.io and choose Connect 4.','Create a match and share the unique link.','Both players open the same link and play.'], scoreMode:'manual', minPlayers:2, animationKey:'race3', tags:['online','board game','connect 4','multiplayer'], playMode:'online', externalProvider:'papergames.io', externalLaunchUrl:'https://papergames.io/en/' },
  { id:'online-doodle-dash', slug:'doodle-dash', behavior:'online', name:'Doodle Dash', shortDescription:'Free drawing, guessing and co-op modes for groups.', description:'Doodle Dash on PlaywithBuddies has several browser drawing modes, including cooperative canvas play.', instructions:['Create a Game Night room.','Open Doodle Dash and make a room.','Share the provider room code/link with your group.','Use Game Night chat while everyone joins the same match.'], scoreMode:'manual', minPlayers:2, animationKey:'sketch', tags:['online','drawing','party','co-op'], playMode:'online', externalProvider:'PlaywithBuddies', externalLaunchUrl:'https://playwithbuddies.com/games/doodle-dash' },
  { id:'online-mini-golf', slug:'mini-golf-online', behavior:'online', name:'Mini Golf Online', shortDescription:'Quick browser mini golf with friends.', description:'PlaywithBuddies offers a free browser mini-golf room for up to four players with shared room codes.', instructions:['Create a Game Night room.','Open Mini Golf on PlaywithBuddies and create a room.','Share the provider room code/link.','Everyone joins the same golf room and plays.'], scoreMode:'manual', minPlayers:2, animationKey:'race5', tags:['online','sports','mini golf','multiplayer'], playMode:'online', externalProvider:'PlaywithBuddies', externalLaunchUrl:'https://playwithbuddies.com/games/mini-golf' },
  { id:'online-battle-pirates', slug:'battle-of-pirates', behavior:'online', name:'Battle of Pirates', shortDescription:'Turn-based naval battles with friends and bots.', description:'Battle of Pirates on PlaywithBuddies is a free browser naval battle with online team modes and optional bots.', instructions:['Create a Game Night room.','Open Battle of Pirates and create a room.','Share the provider room code/link.','Play the naval battle together while coordinating in Game Night.'], scoreMode:'manual', minPlayers:2, supportsTeams:true, animationKey:'race3', tags:['online','strategy','naval','multiplayer'], playMode:'online', externalProvider:'PlaywithBuddies', externalLaunchUrl:'https://playwithbuddies.com/games/battle-of-pirates' },
  { id:'online-gomoku', slug:'gomoku', behavior:'online', name:'Gomoku', shortDescription:'Five-in-a-row online with a friend.', description:'papergames.io offers free Gomoku matches with private friend links in the browser.', instructions:['Create a Game Night room.','Open papergames.io and choose Gomoku.','Create a private game and copy the friend link.','Share or paste the provider link into Game Night so the opponent can launch the same game.'], scoreMode:'manual', minPlayers:2, animationKey:'race3', tags:['online','board game','strategy','multiplayer'], playMode:'online', externalProvider:'papergames.io', externalLaunchUrl:'https://papergames.io/en/gomoku' },
  { id:'online-tic-tac-toe', slug:'tic-tac-toe', behavior:'online', name:'Tic-Tac-Toe', shortDescription:'Quick two-player noughts and crosses online.', description:'papergames.io offers free Tic-Tac-Toe with a private shareable game link and browser play.', instructions:['Create a Game Night room.','Open papergames.io and choose Tic-Tac-Toe.','Create a private game and copy the friend link.','Share or paste the provider link into Game Night so both players launch the same game.'], scoreMode:'manual', minPlayers:2, animationKey:'race3', tags:['online','board game','quick','multiplayer'], playMode:'online', externalProvider:'papergames.io', externalLaunchUrl:'https://papergames.io/en/tic-tac-toe' },
]

export const defaultPrompts: Prompt[] = [
  ...['cat','guitar','pizza','airplane','toothbrush','elephant','football','umbrella','bicycle','rocket'].map((x, i) => ({id:`sketch-${i}`, gameId:'g05', prompt:x, difficulty:'easy' as const})),
  ...['lighthouse','photographer','washing machine','treasure chest','campfire','roller coaster','birthday surprise','traffic jam'].map((x, i) => ({id:`sketch-m-${i}`, gameId:'g05', prompt:x, difficulty:'medium' as const})),
  ...['time machine','underwater restaurant','alien trying to cook','dragon at the airport','robot getting a haircut','haunted supermarket'].map((x, i) => ({id:`sketch-h-${i}`, gameId:'g05', prompt:x, difficulty:'hard' as const})),
  ...['balloon','tree','chair','fish','sun','house','coffee mug','shoe','key','book'].map((x, i) => ({id:`memory-e-${i}`, gameId:'g10', prompt:x, difficulty:'easy' as const})),
  ...['bicycle with basket','person at a bus stop','table with three objects','park bench','kitchen counter','bedroom desk','market stall','simple robot'].map((x, i) => ({id:`memory-m-${i}`, gameId:'g10', prompt:x, difficulty:'medium' as const})),
  ...['busy street scene','game-night table from above','space station control room','crowded restaurant','playground with five objects','imaginary machine with many parts'].map((x, i) => ({id:`memory-h-${i}`, gameId:'g10', prompt:x, difficulty:'hard' as const})),
  ...['What color is the sky?','How many days are in a week?','What do you drink when thirsty?','What animal says meow?','What do you use to cut paper?','What planet do we live on?','What is 2 + 2?','What do you wear on your feet?','What do you open a door with?','What do bees make?'].map((x, i) => ({id:`wrong-${i}`, gameId:'g12', prompt:x})),
  ...['apple','school','phone','river','window','doctor','train','banana','hospital','holiday','garden','music'].map((x, i) => ({id:`contact-${i}`, gameId:'g13', prompt:x})),
]

export function gameBySlug(slug: GameKind) { return defaultGames.find(g => g.slug === slug) }
